on: [push]
jobs:
  testworkflow:
    runs-on: windows-latest
    steps:
      - run: echo "Hello world"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
